from pathlib import Path
import json
ROOT=Path('../ai-dial-chat').resolve();M=json.loads(Path('manifest.json').read_text());SNAP=M['snapshot']
def ref(file,symbol=None):
 lines=(ROOT/file).read_text().splitlines();start=1;end=len(lines)
 if symbol:
  hits=[i for i,l in enumerate(lines) if symbol in l]
  if hits:start=max(1,hits[0]-2);end=min(len(lines),hits[0]+65)
 return {'file':file,'start':start,'end':end,**({'symbol':symbol} if symbol else {})}
def C(*items):return [dict(title=x.split('|')[0],body=x.split('|')[1]) for x in items]
def deck(id,title,series):return {'id':id,'shortTitle':title,'series':series,'snapshot':SNAP,'slides':[]}
def add(d,title,layout='cards',files=None,notes='',**kw):
 sources=[ref(*f) if isinstance(f,tuple) else ref(f) for f in files or ['docs/architecture.md','package.json']]
 d['slides'].append(dict(id=d['id'].replace('/','-')+'-'+str(len(d['slides'])+1).zfill(2),title=title,layout=layout,sources=sources,notes=notes,**kw))
def save(d):
 e=next(x for x in M['decks'] if x['id']==d['id']);p=Path('content/decks')/(d['id'].replace('/','-')+'.json');d['output']=e['output'];p.write_text(json.dumps(d,indent=2)+'\n');e.update(content=str(p),slideCount=len(d['slides']),status='authored',purpose=d['slides'][0].get('subtitle',d['shortTitle']))

O=deck('overview','AI DIAL Chat','Repository overview')
add(O,'AI DIAL Chat','cover',subtitle='A modular chat application, a backend edge, and reusable workspace libraries.',chips=['4 applications','28 libraries','33 technical sessions'],caption='Source snapshot '+SNAP['commit'][:12]+' · '+SNAP['analysisDate'][:10],notes='This series is grounded in the local working tree and Nx graph. It includes one overview plus one deck per application and library. The auxiliary attachment-canvas-consumer-fixture project is in the Nx graph but is not a separate app/library topic. Publishing scripts remain auxiliary tooling. Untracked skill and OpenSpec artifacts are recorded in the manifest. No performance benchmark or production-readiness assertion is made.')
add(O,'Start with the user workflows',cards=C('Converse with context|Choose a deployment, attach files, send messages and inspect evidence.','Reuse knowledge|Browse prompts and skills, then apply them to a conversation.','Manage shared work|Share or publish resources and inspect scheduled task runs.'),files=['apps/chat/src/types/routes.ts','apps/chat/src/pages/Conversation/Conversation.tsx'],notes='The route tree and conversation assembly expose the user workflows shown here. Individual UI libraries implement parts of these flows, while the app supplies state, permissions and backend behavior. Some capabilities depend on configuration and the selected deployment; route existence is not a guarantee that every user can access every feature.')
add(O,'Four apps have different responsibilities','table',headers=['Application','Responsibility'],rows=[['chat','React SPA and application integration'],['chat-api','NestJS BFF, auth, persistence and Core access'],['chat-overlay-sandbox','Browser host for overlay integration cases'],['mcp-app-sandbox','Separate-origin sandbox proxy for MCP UI']],files=['apps/chat/README.md','apps/chat-api/README.md','apps/chat-overlay-sandbox/README.md','apps/mcp-app-sandbox/README.md'],notes='Nx resolves four non-empty projects under apps. The two sandboxes have different purposes: overlay-sandbox is a developer demonstration host, whereas mcp-app-sandbox serves the isolated proxy page required by MCP Apps rendering. Do not merge them into a single deployment assumption.')
add(O,'Libraries for the conversation workspace',cards=C('Conversation|conversation-input, conversation-messages, conversation-panel, conversation-stages','Evidence|attachment-input, attachment-canvas, source-panel, quotations','Navigation|navigation-panel, sidebar, starter-buttons, settings-panel'),notes='These twelve libraries form the main conversation workspace. The input emits send intent, messages display state, history selects conversations, and stages display intermediate progress. Evidence viewers are kept distinct from transport and source derivation. Navigation and sidebar shells let an embedding host choose its own routing and layout.',files=['libs/conversation-input/src/index.ts','libs/attachment-canvas/src/index.ts','libs/navigation-panel/src/index.ts'])
add(O,'Libraries for knowledge and integration',cards=C('Author and discover|catalog, builder-form, prompt-editor, prompts, skill-editor, skills, toolset-editor','Automate and distribute|scheduled-tasks, share, publish-panel, usage-dashboard','Integrate and share code|chat-api-client, chat-hooks, chat-shared, chat-overlay, mcp-apps'),notes='These sixteen libraries complete the set of twenty-eight. The editor packages are distinct from pickers; sharing and publication have separate contracts. The generated client, headless hooks and shared foundations form different layers. Overlay and MCP packages cross browser-frame boundaries and therefore deserve protocol-specific treatment.',files=['libs/catalog/src/index.ts','libs/chat-hooks/src/index.ts','libs/chat-overlay/src/index.ts','libs/mcp-apps/src/index.ts'])
add(O,'Application edges connect the layers','flow',kicker='A simplified ownership map, not a complete dependency graph.',nodes=C('Host / browser|Optional embedding page','apps/chat|Routes, providers, adapters','apps/chat-api|Auth and domain services','External systems|Core, IdP and theme host'),takeaway='UI libraries receive data and behavior through public contracts.',files=['AGENTS.md','apps/chat/src/main.tsx','apps/chat-api/src/app/app.module.ts'],notes='Frontend and backend apps own external integration. Most UI libraries should not know REST paths, identity-provider setup, storage keys or navigation targets. The generated client is a deliberate exception; chat-hooks has a narrower exception for injected generated operations. Some source dependencies currently exceed the stated rule, so the report separates intended isolation from observed dependencies.')
add(O,'One message enters the backend','flow',nodes=C('ConversationInput|onSend intent','Conversation page|Handlers and stream hook','App stream adapter|Host paths and CSRF','Conversation API|POST completions'),takeaway='POST /api/v1/conversations/completions',files=['apps/chat/src/pages/Conversation/Conversation.tsx','apps/chat/src/server-api/chat-stream.api.ts','libs/chat-hooks/src/conversation/create-chat-stream-api.ts','apps/chat-api/src/conversations/conversation.controller.ts'],notes='The browser hands message intent to the app. The app integrates the headless stream behavior and createChatStreamApi, supplying the conversation base path and CSRF callbacks. This endpoint differs from the direct /api/v1/chat/completions proxy. The backend validates the request and owns the persisted conversation lifecycle.')
add(O,'Chunks return through a shared lifecycle','flow',nodes=C('DIAL Core|Upstream response events','Backend relay|Normalize and persist','Stream hook|Merge message changes','Message components|Text, stages and citations'),takeaway='Closing the browser connection is different from explicitly stopping generation.',files=['apps/chat-api/src/conversations/streaming/conversation-streaming.service.ts','apps/chat-api/src/conversations/conversation.controller.ts','libs/chat-hooks/src/conversation/useConversationStream/useConversationStream.ts'],notes='Conversation generation is registered by principal and conversation. The backend saves initial and final or partial state, even when the originating tab disconnects. A dedicated stop request aborts generation, while attach supports resuming a view of active output. The registry is in memory; this is an operational constraint, not durable distributed execution.')
add(O,'Client, hooks and adapters solve different problems','table',headers=['Layer','Concrete role'],rows=[['Generated API client','Fetch operations and DTO serialization'],['Headless hooks','Request/UI lifecycles with injected dependencies'],['Application adapters','Client configuration, CSRF, origin and route mapping'],['UI libraries','Render state and emit typed user actions']],files=['libs/chat-api-client/src/generated/src/runtime.ts','libs/chat-hooks/src/useShareLink/useShareLink.ts','apps/chat/src/server-api/api-client.ts','AGENTS.md'],notes='The generated client is not the server-side DIAL TypeScript SDK. It targets this chat BFF. The backend separately uses DialClientService and the DIAL SDK to call Core. Hooks can depend on generated operation signatures under the documented exception, while the configured client instance remains app-owned.')
add(O,'Compose a view from focused parts','flow',nodes=C('Application state|Messages and deployment','Composer + bubbles|Input and transcript','Evidence surfaces|Stages, citations, canvas','Host callbacks|Send, load and navigate'),takeaway='A library can be adopted without copying the whole route implementation.',files=['apps/chat/src/components/ConversationView/ConversationView.tsx','apps/chat/src/components/ConversationView/ConversationMessageItem.tsx','apps/chat/src/pages/Conversation/Conversation.tsx'],notes='The application assembles components around its contexts and hooks. AssistantMessageBubble accepts afterContent, so the same message component can display a stages panel without owning stage fetching. The canvas is controlled through a provider at the app root. This demonstrates a concrete modularity benefit: presentation composition can change without moving the HTTP contract into the component.')
add(O,'Choose a reuse boundary',cards=C('Reuse a component|Bring typed data, callbacks, labels and its stylesheet.','Build a custom UI|Use chat-hooks and configured generated operations.','Embed the full app|Use ChatOverlay with an existing chat deployment.'),files=['AGENTS.md','libs/chat-hooks/package.json','libs/chat-overlay/README.md','tools/publish-lib.mjs'],notes='All twenty-eight source manifests are private in this snapshot. The verified path is the current workspace with its aliases and Nx graph. Publish and pack tooling exists, but a tag or script is not proof of npm availability. For a separate host, validate the produced package and its peer matrix before proposing installation.')
add(O,'Theme tokens travel from host to component','flow',nodes=C('Theme service|config.json and images','BFF theme proxy|/api/themes','ThemeProvider|CSS vars on html','Library styles|Tokens and overrides'),takeaway='Theme selection is app-owned; reusable libraries consume resolved styling.',files=['docs/theme-customization.md','apps/chat-api/src/themes/theme.controller.ts','apps/chat/src/context/ThemeContext.tsx','libs/chat-shared/src/utils/build-css-vars.ts'],notes='The actual ThemeController is unversioned and exposes /api/themes and /api/themes/icon despite the broader business-route versioning rule. ThemeProvider sets colors as CSS variables. Library props can override local variables, and stable public classes support host styling. The supplied favicon is copied from the adjacent SDK website unchanged.')
add(O,'Localization support has a clear current limit',cards=C('English resources|The current i18n initialization registers en translations.','RTL switching|ar, he, fa and ur set document direction to rtl.','Host-localized libraries|Labels and logical CSS keep language ownership at the edge.'),files=['apps/chat/src/i18n/config.ts','AGENTS.md','libs/navigation-panel/src/models/navigation-panel-props.ts'],notes='Do not equate RTL direction handling with a completed Arabic translation. The current config imports only en.json and falls back to English. The direction hook updates both html.lang and html.dir on language changes. The repository instructions require RTL and accessibility support, but this bundle does not claim a full accessibility conformance audit.')
add(O,'Authentication belongs at the BFF','flow',nodes=C('Browser|Opaque session cookie','Session guard|Validate and refresh','Identity provider|OIDC code flow','Core request|Verified user token'),takeaway='Configured clients and session details stay outside ordinary UI libraries.',files=['docs/auth/auth-bff-encrypted-cookie.md','apps/chat-api/src/auth/session/session.guard.ts','apps/chat-api/src/auth/session/session.service.ts','apps/chat-api/src/auth/refresh/refresh.service.ts'],notes='The default browser flow uses an encrypted HttpOnly session cookie. The backend performs OIDC and refreshes tokens; JavaScript receives user state rather than access or refresh tokens. A separately configured header-token strategy exists. Secure cookie and same-site behavior depend on deployment and overlay mode. This is a description of this source, not general identity-provider setup guidance.')
add(O,'Two upstream APIs share the browser stream','table',headers=['Server flag and deployment','Upstream path'],rows=[['RESPONSES_API_ENABLED = false','Chat Completions'],['Flag true; capability missing/false','Chat Completions'],['Flag true; responsesApi = true','Responses adapter']],files=['docs/responses-api-integration.md','apps/chat-api/src/conversations/streaming/conversation-streaming.service.ts','apps/chat-api/src/conversations/generation/generation-api.ts'],notes='Both the server operator flag and the deployment capability must be true to select Responses. The resolver function alone checks only the capability, so reading it without its caller gives an incomplete rule. The BFF normalizes upstream events to the browser contract. There is no automatic retry through the other API after an error.')
add(O,'Run the applications locally','code',kicker='From the repository root, after configuring backend environment values.',code='npm ci\nnpm run start:all\n\n# Frontend: http://localhost:4207\n# Backend:  http://localhost:5000\n\nnpm exec nx serve chat-overlay-sandbox\nnpm run start:mcp-app-sandbox',caption='Use a Node version compatible with the locked Nx/Vite stack.',files=['package.json','apps/chat/vite.config.mts','apps/chat-api/README.md','apps/mcp-app-sandbox/README.md'],notes='These are documented commands, not operations run against the source repository for this task. Configure DIAL_CORE_URL and the required auth/session settings from apps/chat-api/README.md and .env.template. Configure MCP_APP_SANDBOX_ALLOWED_HOST_ORIGINS before using the separate sandbox. npm ci modifies the consuming checkout, so it is shown for reproducibility and was not run here.')
add(O,'Use the checks that match the change','table',headers=['Purpose','Repository command'],rows=[['Types, lint and tests','npm run verify:full'],['Build the apps/libraries','npm run build:all'],['Check docs and manifests','npm run validate:docs'],['Check generated client drift','npm run openapi:check']],files=['package.json','nx.json'],notes='The repository scripts use Nx targets and affected project selection. The lint script itself applies fixes, while lint:check is the non-mutating alternative used in verification. Full workspace builds and suites were not run for this output-only task. The presentation bundle has its own generation, structural, rendering and example checks.')
add(O,'Modularity gives specific engineering benefits',cards=C('One editor field set|builder-form validation and fields are reused by multiple editors.','Reusable evidence UI|The same canvas displays several typed content kinds.','Replaceable host behavior|Callbacks let a host choose its own routing and persistence.'),files=['libs/builder-form/src/index.ts','libs/toolset-editor/src/components/GeneralForm/GeneralForm.tsx','libs/attachment-canvas/src/models/attachment-canvas.ts','apps/chat/src/components/ConversationView/ConversationMessageItem.tsx'],notes='These are source-backed structural benefits. Shared validation reduces duplicated rule implementations; typed renderers centralize content display; explicit callbacks permit a different host behavior. No speedup, maintenance percentage, adoption count or benchmark is inferred from this structure.')
add(O,'Tradeoffs remain visible',cards=C('Integration is real work|A host must supply data, labels, adapters and the correct peer dependencies.','Boundaries have drift|Some current libs import broader packages than the written rules permit.','Runtime state is local|Generation and several caches rely on process/browser memory.'),files=['AGENTS.md','libs/toolset-editor/package.json','libs/usage-dashboard/src/utils/map-user-usage-to-model-limits.ts','apps/chat-api/src/conversations/conversation-generation.service.ts'],notes='Isolation is a useful design constraint but not a description of every current import. The quality report records concrete counterexamples. Stateful runtime mechanisms also impose deployment and lifecycle concerns. Use these limitations when deciding between component reuse and full-app embedding.')
add(O,'Start with a vertical path through the code',cards=C('Understand the assembly|Read main.tsx, app.tsx and one conversation or editor route.','Trace its contract|Follow a component prop into the host adapter and backend domain.','Reuse one piece|Open that library deck, its full example and its source references.'),files=['apps/chat/src/main.tsx','apps/chat/src/app/app.tsx','apps/chat/src/server-api/api-client.ts'],notes='The series index links all thirty-three decks and their previews. Each library deck includes a diagram, a checked example and source locators. Use manifest.json to see generation and verification status, and qa-report.md to understand the scope and remaining limits. Source paths refer to the recorded working tree snapshot.')
save(O)

F=deck('apps/chat','Chat frontend','Application deep dive');fs=['apps/chat/src/main.tsx','apps/chat/src/app/app.tsx']
add(F,'Chat frontend','cover',subtitle='The React application that assembles reusable features into a coherent workspace.',chips=['React SPA','Application adapters','Port 4207'],caption='apps/chat · @epam/chat',files=fs,notes='This application owns integration, including providers, routing, language, theme, configured API clients and feature availability. Its role is broader than any one component library.')
add(F,'The frontend owns the user workflow',cards=C('Conversation workspace|Send messages, resume history and inspect sources.','Knowledge workflows|Browse and edit prompts, skills, apps and toolsets.','Operations for users|Inspect usage, manage files and work with scheduled tasks.'),files=['apps/chat/src/types/routes.ts'],notes='The route enum and app route registration are the current scope. User-visible capabilities can be gated by server configuration and deployment support.')
add(F,'Bootstrap the application once','flow',nodes=C('main.tsx|React root and imports','BrowserRouter|App-owned routes','Providers|User, theme and config','App|Feature route composition'),takeaway='AttachmentCanvasProvider sits above the routed workspace.',files=fs,notes='main.tsx imports base styles and i18n, creates the tooltip portal, and nests providers before rendering App. RequireAuth guards the main workspace. Login and overlay-close routes are mounted at the higher routing layer.')
add(F,'Providers define state ownership',cards=C('Identity and configuration|UserProvider, AppConfigProvider and UiFeaturesProvider.','Conversation state|ConversationsProvider, GenerationProvider and ClientChannelProvider.','Workspace presentation|ThemeProvider, SourcesSidebarProvider and AttachmentCanvasProvider.'),files=['apps/chat/src/main.tsx'],notes='These are actual provider names from the entry point. Do not move them into libraries to simplify imports. When reusing a component independently, replace the relevant application adapter with explicitly supplied data and callbacks.')
add(F,'Routes connect reusable screens','table',headers=['Route family','Host responsibility'],rows=[['/conversations','Active conversation and history'],['/catalog, /files','Discovery and file operations'],['/prompt-editor, /skill-editor','Load, validate and save authored entities'],['/scheduled-tasks, /settings','Scheduling and usage/settings views']],files=['apps/chat/src/types/routes.ts','apps/chat/src/app/app.tsx'],notes='ROUTES declares more specific variants for edit/detail/callback and invitations. Many route components use React.lazy and Suspense; the conversation page is eagerly prefetched before its lazy wrapper. Do not document every route as loaded in the same way.')
add(F,'Trace a message from UI intent','flow',nodes=C('Composer|Message and attachments','ConversationPage|Host handlers','useConversationStream|State and updates','chat-stream adapter|Transport dependencies'),takeaway='The backend owns persistent conversation writes.',files=['apps/chat/src/pages/Conversation/Conversation.tsx','apps/chat/src/server-api/chat-stream.api.ts','libs/chat-hooks/src/conversation/useConversationStream/useConversationStream.ts'],notes='The page supplies the stream hook and input components with state derived from app contexts. createChatStreamApi receives host paths and CSRF callbacks from the app adapter. Generation result updates flow back into the message components, while persistence remains in the BFF.')
add(F,'Configure the generated client at the edge','code',kicker='Source excerpt · createApiConfiguration in server-api/api-client.ts.',code="new Configuration({\n  basePath: '',\n  credentials: 'include',\n  middleware: [\n    csrfMiddleware,\n    unauthorizedMiddleware,\n    telemetryMiddleware,\n  ],\n});",files=['apps/chat/src/server-api/api-client.ts'],notes='The middleware variables are defined in the source file, not globals. CSRF and unauthorized behavior are supplied through callback-based factories from chat-hooks, with browser/session state remaining app-owned. Full source-linked contract information is in the bundle index.')
add(F,'Assemble evidence around each message',cards=C('Transcript|ConversationMessageItem composes message bubbles and stages.','Sources|ConversationSourcesPanel adapts source data and open actions.','Canvas|The app resolves files and passes renderer dependencies.'),files=['apps/chat/src/components/ConversationView/ConversationMessageItem.tsx','apps/chat/src/components/ConversationSourcesPanel/ConversationSourcesPanel.tsx','apps/chat/src/app/app.tsx'],notes='These application containers connect source-derived message data to generic display components. URL resolution, PDF worker setup and feature flags should be inspected at this edge rather than inferred from the presentation component alone.')
add(F,'Theme, locale and viewport are host concerns',cards=C('ThemeProvider|Loads theme configuration and writes CSS variables.','i18n initialization|Registers English and updates html direction on language changes.','Responsive branches|App hooks provide mobile/desktop decisions to feature surfaces.'),files=['apps/chat/src/context/ThemeContext.tsx','apps/chat/src/i18n/config.ts','apps/chat/src/hooks/breakpoint/useBreakpoint.ts'],notes='The frontend currently registers only English translations. RTL direction switching exists for four base language codes. This is support infrastructure, not a claim of complete translated Arabic UI. Component demos in this bundle use English and clearly identified synthetic data.')
add(F,'A concrete extension: message content slots','code',kicker='Runnable composition pattern from examples/conversation-messages.tsx.',code='<AssistantMessageBubble\n  text="**Demo:** evidence collected."\n  isStreaming={false}\n  deploymentDisplayName="Demo assistant"\n  afterContent={\n    <StagesPanel stages={[]} isStreaming={false} />\n  }\n/>',files=['libs/conversation-messages/src/models/message-bubble.ts','apps/chat/src/components/ConversationView/ConversationMessageItem.tsx'],notes='The complete checked example imports both components and stylesheets. afterContent renders between the message body and actions. Replace the empty demo stages with the host message stages; no backend code change is required to use the slot.')
add(F,'Run and build the frontend','code',kicker='Commands run from the repository root.',code='npm start\n# Vite: http://localhost:4207\n# /api is proxied to http://localhost:5000\n\nnpm exec nx run @epam/chat:build\nnpm exec nx run @epam/chat:typecheck\nnpm exec nx run @epam/chat:test',files=['package.json','apps/chat/vite.config.mts'],notes='Nx resolves the application name as @epam/chat. npm start uses the supported chat alias. These commands are provided for the reader; no source build or application dependency installation was performed for this documentation task. Vite configuration and the graph, rather than an old README project count, determine the targets.')
add(F,'Inspect behavior through existing tests','table',headers=['Test area','Evidence'],rows=[['Conversation route','ConversationRoute integration and unit specs'],['Message composition','ConversationMessageItem specs'],['Provider behavior','OverlayContext and app-level context specs'],['API adapters','server-api tests for transport integration']],files=['apps/chat/src/pages/ConversationRoute/ConversationRoute.integration.spec.tsx','apps/chat/src/components/ConversationView/tests/ConversationMessageItem.spec.tsx','apps/chat/src/context/overlay/tests/OverlayContext.spec.tsx'],notes='Tests are inspected evidence, not newly executed application suite results. For a future code change, select the relevant Nx test target or npm run test:file. Presentation example modules were checked independently with strict TypeScript against the same source exports.')
add(F,'Integration limits are part of the design',cards=C('Providers are coupled|The full app composition has many coordinated state owners.','Backend required|A running UI alone cannot authenticate or complete conversations.','Some adapter gaps remain|Audio transcription retains a documented raw DTO wrapper.'),files=['apps/chat/src/main.tsx','apps/chat/src/server-api/chat.api.ts','apps/chat-api/README.md'],notes='The raw transcription wrapper documents the customContent versus custom_content schema collision. Do not claim every HTTP call is generated. For a smaller host, adopt a component or focused hook entry before copying the entire provider tree.')
add(F,'Follow one feature end to end','flow',nodes=C('Route|Choose a user workflow','Container|Resolve context and data','Library contract|Render and emit intent','Server adapter|Perform the operation'),takeaway='Start in apps/chat/src/pages, then follow imports into libs and server-api.',files=['apps/chat/src/pages/PromptEditor/PromptEditor.tsx','apps/chat/src/server-api/api-client.ts','libs/prompt-editor/src/models/prompt-editor-props.ts'],notes='PromptEditor is a manageable example: the app loads and saves the entity while the library owns the fields. The same tracing method scales to conversations. Consult each library deck for the exact exported prop and callback contract.')
save(F)

B=deck('apps/chat-api','Chat backend','Application deep dive');bf=['apps/chat-api/src/main.ts','apps/chat-api/src/app/app.module.ts']
add(B,'Chat backend','cover',subtitle='The NestJS edge that authenticates users, persists conversations and adapts DIAL Core.',chips=['Backend contracts','Generation lifecycle','Port 5000'],caption='apps/chat-api · @epam/chat-api',files=bf,notes='chat-api is the backend-for-frontend for the React application. It also serves production frontend assets and coordinates several external systems. Distinguish its generated browser client from the server-side DIAL TypeScript SDK.')
add(B,'Keep three boundaries explicit',cards=C('Browser contract|Validated HTTP requests, DTOs and SSE responses.','Application services|Conversation lifecycle, auth policy and domain coordination.','External systems|DIAL Core, OIDC providers, theme host and telemetry exporters.'),files=bf+['apps/chat-api/src/dial/dial-client.service.ts'],notes='Controllers delegate to services. DialClientService centralizes Core SDK configuration and the fetch user-agent behavior. Non-Core integrations can use their own transport where required; do not describe all outbound calls as one SDK operation.')
add(B,'Bootstrap establishes cross-cutting behavior','flow',nodes=C('Telemetry import|Before framework loading','Nest application|Modules and config','Middleware / guards|Headers and validation','Routes + assets|API and SPA responses'),takeaway='Strict ValidationPipe rejects unknown request fields.',files=bf,notes='main.ts imports telemetry first, sets validation, CORS, cookie handling, URI versioning and static middleware, and enables graceful shutdown. Source comments explain ordering constraints. The environment schema controls boot-time validation; the source contains both ConfigService reads and some direct process.env reads.')
add(B,'Domain modules organize the backend','table',headers=['Domain family','Examples'],rows=[['Conversation execution','conversations, chat, client-channel'],['Knowledge and resources','deployments, applications, files, skills, prompts'],['Sharing and automation','share, publish, scheduled-tasks'],['Platform behavior','auth, app-config, themes, telemetry']],files=['apps/chat-api/src/app/app.module.ts'],notes='Domain folders sit directly under src. Auxiliary concerns such as schemas, offline credentials, health and user configuration are also wired by AppModule. The table groups the modules for readability and does not replace the source module index.')
add(B,'Representative HTTP contracts','table',headers=['Operation','Current path'],rows=[['List deployments','GET /api/v1/deployments'],['Generate a conversation','POST /api/v1/conversations/completions'],['Current user','GET /api/v1/auth/me'],['Theme configuration','GET /api/themes']],files=['apps/chat-api/src/deployments/deployments.controller.ts','apps/chat-api/src/conversations/conversation.controller.ts','apps/chat-api/src/auth/auth.controller.ts','apps/chat-api/src/themes/theme.controller.ts'],notes='The main business domains use URI versioning, but themes are still unversioned in the implementation. This is a concrete exception to the written rule, not a typo to silently correct in the slides. Swagger handler names feed operation ids and the generated client.')
add(B,'A completion has a persisted lifecycle','flow',nodes=C('Request / principal|Validate and authorize','Save start state|User and placeholder','Relay generation|Accumulate chunks','Save terminal state|Complete, stopped or failed'),takeaway='Backend persistence survives the originating browser disconnect.',files=['apps/chat-api/src/conversations/conversation.controller.ts','apps/chat-api/src/conversations/streaming/conversation-streaming.service.ts','apps/chat-api/src/conversations/conversation-generation.service.ts'],notes='The controller intentionally does not stop generation when the response disconnects. Generation services retain the active operation in memory and persist terminal or partial results. Dedicated stop and attach operations support user control and reopening a running conversation. Process-local state requires deployment consideration.')
add(B,'Upstream dispatch is controlled on the server','table',headers=['Condition','Outcome'],rows=[['Operator flag disabled','Use Chat Completions'],['Flag enabled; capability absent','Use Chat Completions'],['Flag enabled; responsesApi true','Use ResponsesAdapter']],files=['apps/chat-api/src/conversations/streaming/conversation-streaming.service.ts','apps/chat-api/src/conversations/generation/generation-api.ts','docs/responses-api-integration.md'],notes='The deployment is re-resolved under the current user token. Both the operator flag and capability matter; the small pure resolver by itself shows only the capability check. The browser sees the same normalized completion contract. Failed requests are not automatically retried through another generation API.')
add(B,'Authentication has explicit request scope','flow',nodes=C('Browser cookie|Encrypted session','Session strategy|Verify / refresh','SessionGuard|Set request identity','Domain service|Call Core with token'),takeaway='Header-token authentication is a separately configured strategy.',files=['apps/chat-api/src/auth/session/session.guard.ts','apps/chat-api/src/auth/strategies/cookie-session.strategy.ts','apps/chat-api/src/auth/strategies/header-token.strategy.ts','apps/chat-api/src/auth/session/session.service.ts'],notes='The cookie payload carries encrypted tokens; browser JavaScript does not receive their values. The header strategy is enabled through configuration and verifies allowed issuer/provider identity. Per-request principal and auth data must not be stored in a mutable service singleton.')
add(B,'Keep controller and DTO changes synchronized','code',kicker='Source excerpt from ChatController · direct completion proxy.',code="@Controller({ path: 'chat', version: '1' })\nexport class ChatController {\n  @Post('completions')\n  sendCompletion(@Req() req: Request,\n                 @Body() dto: ChatCompletionDto) {\n    const { at } = req.user as SessionUser;\n    return this.chatService.sendCompletion(dto, at);\n  }\n}",files=['apps/chat-api/src/chat/chat.controller.ts','apps/chat-api/src/chat/dto/chat-completion.dto.ts'],notes='This is an abridged source excerpt, not a new runnable controller. Imports, constructor injection and Swagger decorators are omitted for readability; the original source contains them. This direct /chat/completions endpoint is distinct from the conversation persistence and streaming workflow. Full source excerpts are retained by path and range in the index.')
add(B,'Regenerate the browser contract after API changes','flow',nodes=C('Controller + DTO|Swagger annotations','OpenAPI export|openapi-spec','Client generation|openapi-sdk','Drift check|openapi:check'),takeaway='npm run openapi runs the complete regeneration workflow.',files=['package.json','tools/openapi/check-client.mjs','apps/chat-api/src/openapi/openapi.config.ts','libs/chat-api-client/src/index.ts'],notes='The generated client is checked in. Update server definitions rather than editing generated methods. The operationIdFactory uses handler names, so naming the handler changes the browser-facing method. Commands shown here were not run because they would modify the repository artifacts.')
add(B,'Configure the runtime deliberately','table',headers=['Configuration','Responsibility'],rows=[['DIAL_CORE_URL','Core transport endpoint'],['AUTH_* settings','Session keys and provider configuration'],['RESPONSES_API_ENABLED','Server-only upstream dispatch switch'],['MCP_APP_SANDBOX_URL','Separate-origin MCP proxy URL']],files=['apps/chat-api/README.md','apps/chat-api/src/config/environment.config.ts'],notes='The exact required fields and defaults are in the backend README and environment schema. Use obvious demo values when experimenting; do not embed real secrets in code examples. Invalid required configuration fails at boot. The runtime also supports feature, theme, cookie and telemetry settings.')
add(B,'Run and verify the backend','code',kicker='From the repository root with configured environment values.',code='npm run start:api\n\nnpm exec nx run @epam/chat-api:typecheck\nnpm exec nx run @epam/chat-api:test\nnpm run build:api\n\n# API documentation is configured in main.ts.\n# Use the deployment environment reference for auth.',files=['package.json','apps/chat-api/src/main.ts'],notes='Nx resolves @epam/chat-api as the project name. The serve target builds/runs the backend, while the separate start:api:dev script uses HMR tooling. These application commands are documented, not run during presentation generation. Backend integration tests use mocked external clients.')
add(B,'Existing tests exercise contracts and failures','table',headers=['Area','Source evidence'],rows=[['Conversation controller','SSE, attach, errors and persistence integration specs'],['Authentication','Session, CSRF and strategy specs'],['Domain transport','Chat controller and service specs'],['Sandbox/static assets','App-owned asset and policy behavior tests']],files=['apps/chat-api/src/conversations/tests/conversation.controller.integration.spec.ts','apps/chat-api/src/auth/session/tests/session.guard.spec.ts','apps/chat-api/src/chat/tests/chat.controller.integration.spec.ts'],notes='The inspected test files provide concrete behavior expectations. Test presence alone is not a passing suite result, and the presentation QA does not substitute for backend security testing. Run focused tests and repository verification for a code change.')
add(B,'Operational tradeoffs shape deployment',cards=C('Process-local state|Generation registries and caches are not durable cross-pod coordination.','External dependencies|Core and identity-provider availability affect user workflows.','Policy exceptions exist|Unversioned themes and documented transport gaps remain in the source.'),files=['apps/chat-api/src/conversations/conversation-generation.service.ts','apps/chat-api/src/app/cache.config.ts','apps/chat-api/src/themes/theme.controller.ts'],notes='Encrypted-cookie authentication enables stateless session decryption across correctly configured pods, but it does not make every runtime mechanism distributed. Distinguish session storage from in-memory active-generation coordination. Use deployment-specific operational checks before adopting a multi-instance topology.')
save(B)

S=deck('apps/chat-overlay-sandbox','Overlay sandbox','Sandbox walkthrough');sf=['apps/chat-overlay-sandbox/README.md','apps/chat-overlay-sandbox/src/main.tsx']
add(S,'Overlay sandbox','cover',subtitle='A real browser host for exercising the chat overlay protocol.',chips=['Integration cases','Port 4300','Running chat required'],caption='apps/chat-overlay-sandbox',files=sf,notes='This is a React/Vite demonstration application, not an isolated MCP resource renderer. It hosts existing overlay clients against a running chat instance.')
add(S,'Each case demonstrates a distinct contract','table',headers=['Case','Demonstration'],rows=[['DirectOverlayCase','Mount into a host-owned region'],['ManagerOverlayCase','Floating widget controls'],['ConversationListCase','List, create, select, rename and delete'],['Features / auth cases','Live options and provider login UI modes']],files=['apps/chat-overlay-sandbox/README.md'],notes='EnabledFeaturesCase and AuthUiModeCase complete the set. Cases are actual source modules under src/cases. They are useful for reproducing integration behavior before embedding the overlay into a separate product.')
add(S,'Trace the host-to-chat handshake','flow',nodes=C('Sandbox page|Choose an integration case','ChatOverlay|Create iframe','Embedded chat|Readiness exchange','Host controls|Send requests / read events'),takeaway='Host allowlisting and overlay mode are prerequisites.',files=['libs/chat-overlay/src/lib/ChatOverlay.ts','apps/chat-overlay-sandbox/src/cases/DirectOverlayCase/DirectOverlayCase.tsx'],notes='The host API waits for the full ready-to-interact handshake. A blank iframe caused by frame-ancestors policy is not a protocol timeout to fix in the controls. Check server allowlisting and runtime overlay mode first.')
add(S,'Reproduce the local scenario','code',kicker='Configure the backend, then run both the chat and this sandbox.',code='OVERLAY_ENABLED=true\nALLOWED_IFRAME_ORIGINS=http://localhost:4300\n\n# In the shell that starts the sandbox:\nVITE_CHAT_OVERLAY_HOST=http://localhost:4207 \\\n  npm exec nx serve chat-overlay-sandbox',files=['apps/chat-overlay-sandbox/README.md','apps/chat-overlay-sandbox/vite.config.mts'],notes='The first two lines are backend environment configuration, not values to set only on the sandbox process. The host override is passed to the Vite sandbox. Run chat at 4207 and its backend at 5000 first. No real user data is required to open the page, but an authenticated deployment may require login for chat actions.')
add(S,'A direct overlay is a small integration','code',kicker='Checked pattern from examples/chat-overlay.ts.',code="const overlay = new ChatOverlay('#demo-chat', {\n  domain: 'http://localhost:4207',\n  theme: 'dark',\n});\nawait overlay.ready();\nawait overlay.setInputContent('Explain the demo');\n// Later: overlay.destroy();",files=['apps/chat-overlay-sandbox/src/cases/DirectOverlayCase/DirectOverlayCase.tsx','libs/chat-overlay/src/lib/ChatOverlay.ts'],notes='The complete example receives domain as a parameter, subscribes to an event and returns cleanup. The container must exist in the page. Changing input is a protocol operation; it does not automatically send a model request.')
add(S,'Deployment shares the main chat image',cards=C('Published route|The backend can serve the sandbox at /overlay-sandbox/.','Enable it explicitly|OVERLAY_SANDBOX_ENABLED controls exposure of the route.','Separate HTML policy|The backend supplies the sandbox style nonce and response policy.'),files=['apps/chat-overlay-sandbox/README.md','Dockerfile','apps/chat-api/src/app/static-assets.ts'],notes='The root Dockerfile builds this app with the frontend and backend. The deployed sandbox embeds the current origin. This same-origin deployment is intentional for this demo host and must not be copied to the MCP sandbox architecture.')
add(S,'Verify cases through the current targets','code',kicker='Nx targets come from the resolved project graph.',code='npm exec nx test chat-overlay-sandbox\nnpm exec nx build chat-overlay-sandbox\nnpm exec nx run chat-overlay-sandbox:typecheck',files=['apps/chat-overlay-sandbox/README.md','apps/chat-overlay-sandbox/package.json'],notes='The source includes seven test files for sandbox behavior. These suites were inspected but not run for the presentation task. The live integration requires the external chat deployment and its server policy, beyond what a mocked test can establish.')
add(S,'Interpret integration failures at the right layer',cards=C('Blank frame|Check chat CSP frame-ancestors and allowed host origin.','No ready event|Inspect protocol readiness after the iframe loads.','Login cannot complete|Verify the exact provider and configured UI mode.'),files=['apps/chat-overlay-sandbox/README.md','libs/chat-overlay/src/lib/ChatOverlay.ts'],notes='Same-window identity-provider login in an iframe depends on the provider tenant and browser policy. The sandbox exposes those choices for investigation; it cannot make an incompatible provider embeddable. Use it as a reproducible integration host rather than a proof of production compatibility.')
save(S)

S=deck('apps/mcp-app-sandbox','MCP sandbox proxy','Sandbox walkthrough');mf=['apps/mcp-app-sandbox/README.md','apps/mcp-app-sandbox/src/main.ts']
add(S,'MCP sandbox proxy','cover',subtitle='A separate-origin HTML bridge for the MCP Apps double-iframe boundary.',chips=['NestJS proxy page','Port 3100','Allowlist required'],caption='apps/mcp-app-sandbox',files=mf,notes='This small application serves the sandbox-proxy document used by the MCP UI renderer. It must be deployed on an origin distinct from the chat host. It is an infrastructure component of the rendering boundary, not a catalog demo.')
add(S,'Why a separate application exists','flow',nodes=C('Chat host|Trusted app origin','Proxy frame|Distinct host or port','Inner tool frame|Untrusted UI document','Message bridge|Validated communication'),takeaway='Same-origin hosting would defeat the intended isolation boundary.',files=mf+['apps/mcp-app-sandbox/src/app/sandbox-page.ts'],notes='The README and implementation adapt the MCP reference double-iframe pattern. A sandbox attribute alone is not the reason for this separate app; the distinct origin keeps the proxy and tool document out of the host origin. The inner document and bridge have their own constraints.')
add(S,'Request validation precedes HTML delivery','flow',nodes=C('GET /|Origin or Referer','Allowlist check|Resolve host origin','Denied request|403 when invalid','Allowed response|HTML and scoped CSP'),takeaway='No allowlist means no successful page response.',files=['apps/mcp-app-sandbox/src/app/sandbox.controller.ts','apps/mcp-app-sandbox/src/app/sandbox.service.ts'],notes='SandboxService uses an Origin header when present, then falls back to the Referer origin. A missing or unapproved origin is rejected. SandboxController sends text/html, CSP, nosniff, cross-origin resource policy and no-store. A raw GET without the required embedding context should fail.')
add(S,'Configure two sides of the connection','code',kicker='The sandbox origin must differ from the chat origin.',code='# Start the sandbox:\nMCP_APP_SANDBOX_ALLOWED_HOST_ORIGINS=http://localhost:4207 \\\n  npm exec nx serve mcp-app-sandbox\n\n# Configure chat-api separately:\nMCP_APP_SANDBOX_URL=http://localhost:3100',files=['apps/mcp-app-sandbox/README.md','apps/mcp-app-sandbox/src/config/environment.config.ts'],notes='The frontend receives the sandbox URL through the backend client-configuration pipeline. PORT defaults to 3100. Production should use the actual distinct HTTPS origins and the intended host allowlist. No secret values are required in this example.')
add(S,'The page and policy are app-owned',cards=C('Controller|Validates the caller context and sets response headers.','Service|Combines allowed origin, HTML and CSP construction.','Page builder|Creates the bridge document used by the nested renderer.'),files=['apps/mcp-app-sandbox/src/app/sandbox.controller.ts','apps/mcp-app-sandbox/src/app/sandbox.service.ts','apps/mcp-app-sandbox/src/app/csp.ts','apps/mcp-app-sandbox/src/app/sandbox-page.ts'],notes='main.ts intentionally disables Helmet generic CSP and frame blocking so the route can deliver its custom embedding policy. CORS is explicitly disabled for cross-origin script fetching. This route is designed for iframe navigation with origin validation, not a general data API.')
add(S,'A rendered MCP view needs the whole chain','flow',nodes=C('Message evidence|Tool and resource match','Host adapter|Fetch resource / call tool','MCP renderer|Configured sandbox URL','Proxy page|Nested UI lifecycle'),takeaway='Use the mcp-apps and attachment-canvas decks for the frontend contracts.',files=['libs/mcp-apps/src/models/mcp-apps.ts','libs/attachment-canvas/src/components/McpAppCanvasRenderer/McpAppCanvasRenderer.tsx','apps/mcp-app-sandbox/src/app/sandbox-page.ts'],notes='The sandbox alone does not discover tools or authenticate tool calls. Those operations are supplied by the host adapter and backend. To reproduce a full interaction, use a configured MCP-capable deployment and a real ui:// resource; this bundle does not manufacture a product screenshot of that interaction.')
add(S,'Build and check what exists','code',kicker='The resolved project has build, serve, lint and typecheck; no test target.',code='npm exec nx build mcp-app-sandbox\nnpm exec nx run mcp-app-sandbox:typecheck\nnpm exec nx run mcp-app-sandbox:lint\n\ndocker build -f apps/mcp-app-sandbox/Dockerfile \\\n  -t mcp-app-sandbox .',files=['apps/mcp-app-sandbox/package.json','apps/mcp-app-sandbox/README.md','apps/mcp-app-sandbox/Dockerfile'],notes='No source test files or test target were discovered for this application. Do not invent a passing test result or recommend a nonexistent target. Build/typecheck/lint commands are available; real isolation behavior needs a browser integration exercise with distinct origins.')
add(S,'Limits to carry into operations',cards=C('Exact origin matters|A host allowlist must match the deployed scheme, hostname and port.','Not a content service|The app serves a proxy document, not Core storage or user files.','Validation gap|No dedicated source tests were discovered in this project.'),files=mf+['apps/mcp-app-sandbox/src/app/sandbox.service.ts'],notes='The small source footprint does not reduce the importance of this boundary. Deployment-origin and browser-policy checks remain necessary. The presentation report records that no full live MCP/Core integration was exercised during this output-only documentation task.')
save(S)
Path('manifest.json').write_text(json.dumps(M,indent=2)+'\n');print('Authored overview and four app decks:',[(e['id'],e.get('slideCount')) for e in M['decks'] if not e['id'].startswith('libs/')])
